basePath: /
consumes:
- application/json
definitions:
  Login:
    properties:
      email:
        type: string
        x-go-name: Email
      password:
        type: string
        x-go-name: Password
      userID:
        type: string
        x-go-name: UserID
    type: object
    x-go-package: github.com/nik/JWTDemo/model
host: some-url.com
info:
  description: Documentation of our awesome API.
  title: awesome.
  version: 1.0.0
paths:
  /login:
    post:
      description: Verifies user login credentials
      operationId: idOfLoginEndpoint
      responses:
        "200":
          $ref: '#/responses/LoginResponse'
      tags:
      - login-tag
produces:
- application/json
responses:
  LoginResponse:
    description: This text will appear as description of your response body.
    schema:
      $ref: '#/definitions/Login'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
